services:
  - type: web
    name: dog-adoption-api
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: dog_adoption_prod
      - key: JWT_SECRET
        sync: false
